language: elixir
sudo: false
notifications:
  email: false

elixir:
  - 1.7

otp_release:
  - 21.2

addons:
  postgresql: "9.5"

env:
  - MIX_ENV=test

script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix do compile --warnings-as-errors --force
  - mix format --check-formatted
  - mix test

cache:
  directories:
    - _build
    - deps
