language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot elixir-companies.toml --allow-redirect -w agilion.com,brighterlink.io,dubber.net,therealreal.com,marketfactory.com
