on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Elixir
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 21.1
          elixir-version: 1.7.4
      - name: Install Dependencies
        run: mix deps.get
      - name: Check formatting
        run: mix format --check-formatted
      - name: Compile project
        run: mix compile --warnings-as-errors
      - name: Run Tests
        run: mix test
