# This file is synced with beam-community/common-config. Any changes will be overwritten.

name: Publish Docs

on:
  workflow_dispatch:

concurrency:
  group: hex-publish-docs
  cancel-in-progress: true

jobs: {}
